### ISSUE TITLE
When selecting Type = "file-version" pipes show up in node list too

### ISSUE THREAD

**Issue by gk3758** [cadets/cadets-ui#87]
@trombonehero was there a reason for file-version to be searched using the "Global" tag and not the "File" tag. This was what was causing pipes to show up in the NodeSearchsheet's node list when selecting Type = "file-version" because pipes also share the "Global" tag in the database.

**Comment by HarkonenBade** [comment]
I think the only reasoning for that originally was that any uuids that are created via being referenced in a read or write call are only tagged as 'Global' and would otherwise never appear in the graph. It may be worth seeing if we can do a separate search specifically for nodes the have the 'Global' tag but lack any of the other normal global tags such as 'File', 'Pipe' or 'Socket'.
